# import = ["/home/aus/.config/alacritty/themes/themes/carbonfox.yml"]
#tabspaces = 4

[terminal]
#shell = "wsl"
#working_directory = "$wsl"
#shell = { program = "cmd", args = "wsl" }
shell = { program = "powershell", args = ["-nologo"] }
#shell = { program = "wsl", args = ["-d", "Arch"] }


[general]
import = [
    "~/.config/alacritty/themes/themes/one_dark.toml"
]

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 16

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[window]
decorations = "none"
opacity = 1

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 150
lines = 50

[window.padding]
x = 0
y = 0
